@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedGigabyteData" as VersionedGigabyteData MODEL_COLOR
end box

[-> Model : undoGigabyteData()
activate Model

Model -> VersionedGigabyteData : undo()
activate VersionedGigabyteData

VersionedGigabyteData -> VersionedGigabyteData :resetData(ReadOnlyGigabyteData)
VersionedGigabyteData --> Model :
deactivate VersionedGigabyteData

[<-- Model
deactivate Model

@enduml
