@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "undo"

package States <<rectangle>> {
    class State1 as "<u>gigabyte0:GigabyteData</u>"
    class State2 as "<u>gigabyte1:GigabyteData</u>"
    class State3 as "<u>gigabyte2:GigabyteData</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
